# deployment manifest

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: fastapi-app2:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
---

# service manifest
apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP
